// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public interface AuthRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.liangke.tcp.packet.AuthRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *鉴权结果
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.AuthResult result = 2;</code>
   */
  int getResultValue();
  /**
   * <pre>
   *鉴权结果
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.AuthResult result = 2;</code>
   */
  com.liangke.tcp.packet.AuthResult getResult();

  /**
   * <pre>
   *鉴权KEY
   * </pre>
   *
   * <code>string securityKey = 3;</code>
   */
  String getSecurityKey();
  /**
   * <pre>
   *鉴权KEY
   * </pre>
   *
   * <code>string securityKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getSecurityKeyBytes();
}
