// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

/**
 * <pre>
 **
 * 聊天响应
 * </pre>
 *
 * Protobuf type {@code com.liangke.tcp.packet.ChatRespBody}
 */
public  final class ChatRespBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.liangke.tcp.packet.ChatRespBody)
    ChatRespBodyOrBuilder {
  // Use ChatRespBody.newBuilder() to construct.
  private ChatRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatRespBody() {
    time_ = 0L;
    type_ = 0;
    text_ = "";
    fromId_ = 0;
    fromHeadUrl_ = "";
    fromNick_ = "";
    toId_ = 0;
    toNick_ = "";
    group_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ChatRespBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 32: {

            fromId_ = input.readInt32();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            fromHeadUrl_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            fromNick_ = s;
            break;
          }
          case 56: {

            toId_ = input.readInt32();
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            toNick_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            group_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Chat.internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Chat.internal_static_com_liangke_tcp_packet_ChatRespBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChatRespBody.class, Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
   */
  public com.liangke.tcp.packet.ChatType getType() {
    com.liangke.tcp.packet.ChatType result = com.liangke.tcp.packet.ChatType.valueOf(type_);
    return result == null ? com.liangke.tcp.packet.ChatType.UNRECOGNIZED : result;
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  private volatile Object text_;
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  public String getText() {
    Object ref = text_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    Object ref = text_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMID_FIELD_NUMBER = 4;
  private int fromId_;
  /**
   * <pre>
   *发送聊天消息的用户id
   * </pre>
   *
   * <code>int32 fromId = 4;</code>
   */
  public int getFromId() {
    return fromId_;
  }

  public static final int FROMHEADURL_FIELD_NUMBER = 5;
  private volatile Object fromHeadUrl_;
  /**
   * <pre>
   *发送聊天信息用户URL
   * </pre>
   *
   * <code>string fromHeadUrl = 5;</code>
   */
  public String getFromHeadUrl() {
    Object ref = fromHeadUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fromHeadUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送聊天信息用户URL
   * </pre>
   *
   * <code>string fromHeadUrl = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFromHeadUrlBytes() {
    Object ref = fromHeadUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fromHeadUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMNICK_FIELD_NUMBER = 6;
  private volatile Object fromNick_;
  /**
   * <pre>
   *发送聊天消息的用户nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  public String getFromNick() {
    Object ref = fromNick_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fromNick_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送聊天消息的用户nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  public com.google.protobuf.ByteString
      getFromNickBytes() {
    Object ref = fromNick_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fromNick_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOID_FIELD_NUMBER = 7;
  private int toId_;
  /**
   * <pre>
   *目标用户id
   * </pre>
   *
   * <code>int32 toId = 7;</code>
   */
  public int getToId() {
    return toId_;
  }

  public static final int TONICK_FIELD_NUMBER = 8;
  private volatile Object toNick_;
  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 8;</code>
   */
  public String getToNick() {
    Object ref = toNick_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      toNick_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 8;</code>
   */
  public com.google.protobuf.ByteString
      getToNickBytes() {
    Object ref = toNick_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      toNick_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_FIELD_NUMBER = 9;
  private volatile Object group_;
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 9;</code>
   */
  public String getGroup() {
    Object ref = group_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 9;</code>
   */
  public com.google.protobuf.ByteString
      getGroupBytes() {
    Object ref = group_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (type_ != com.liangke.tcp.packet.ChatType.CHAT_TYPE_UNKNOW.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
    }
    if (fromId_ != 0) {
      output.writeInt32(4, fromId_);
    }
    if (!getFromHeadUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fromHeadUrl_);
    }
    if (!getFromNickBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fromNick_);
    }
    if (toId_ != 0) {
      output.writeInt32(7, toId_);
    }
    if (!getToNickBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, toNick_);
    }
    if (!getGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, group_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (type_ != com.liangke.tcp.packet.ChatType.CHAT_TYPE_UNKNOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
    }
    if (fromId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, fromId_);
    }
    if (!getFromHeadUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fromHeadUrl_);
    }
    if (!getFromNickBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fromNick_);
    }
    if (toId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, toId_);
    }
    if (!getToNickBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, toNick_);
    }
    if (!getGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, group_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChatRespBody)) {
      return super.equals(obj);
    }
    ChatRespBody other = (ChatRespBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && type_ == other.type_;
    result = result && getText()
        .equals(other.getText());
    result = result && (getFromId()
        == other.getFromId());
    result = result && getFromHeadUrl()
        .equals(other.getFromHeadUrl());
    result = result && getFromNick()
        .equals(other.getFromNick());
    result = result && (getToId()
        == other.getToId());
    result = result && getToNick()
        .equals(other.getToNick());
    result = result && getGroup()
        .equals(other.getGroup());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + FROMID_FIELD_NUMBER;
    hash = (53 * hash) + getFromId();
    hash = (37 * hash) + FROMHEADURL_FIELD_NUMBER;
    hash = (53 * hash) + getFromHeadUrl().hashCode();
    hash = (37 * hash) + FROMNICK_FIELD_NUMBER;
    hash = (53 * hash) + getFromNick().hashCode();
    hash = (37 * hash) + TOID_FIELD_NUMBER;
    hash = (53 * hash) + getToId();
    hash = (37 * hash) + TONICK_FIELD_NUMBER;
    hash = (53 * hash) + getToNick().hashCode();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChatRespBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatRespBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatRespBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatRespBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatRespBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatRespBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatRespBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChatRespBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatRespBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatRespBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChatRespBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 聊天响应
   * </pre>
   *
   * Protobuf type {@code com.liangke.tcp.packet.ChatRespBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.liangke.tcp.packet.ChatRespBody)
      com.liangke.tcp.packet.ChatRespBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_com_liangke_tcp_packet_ChatRespBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatRespBody.class, Builder.class);
    }

    // Construct using com.liangke.tcp.packet.ChatRespBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      type_ = 0;

      text_ = "";

      fromId_ = 0;

      fromHeadUrl_ = "";

      fromNick_ = "";

      toId_ = 0;

      toNick_ = "";

      group_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Chat.internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor;
    }

    public ChatRespBody getDefaultInstanceForType() {
      return ChatRespBody.getDefaultInstance();
    }

    public ChatRespBody build() {
      ChatRespBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ChatRespBody buildPartial() {
      ChatRespBody result = new ChatRespBody(this);
      result.time_ = time_;
      result.type_ = type_;
      result.text_ = text_;
      result.fromId_ = fromId_;
      result.fromHeadUrl_ = fromHeadUrl_;
      result.fromNick_ = fromNick_;
      result.toId_ = toId_;
      result.toNick_ = toNick_;
      result.group_ = group_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChatRespBody) {
        return mergeFrom((ChatRespBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChatRespBody other) {
      if (other == ChatRespBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.getFromId() != 0) {
        setFromId(other.getFromId());
      }
      if (!other.getFromHeadUrl().isEmpty()) {
        fromHeadUrl_ = other.fromHeadUrl_;
        onChanged();
      }
      if (!other.getFromNick().isEmpty()) {
        fromNick_ = other.fromNick_;
        onChanged();
      }
      if (other.getToId() != 0) {
        setToId(other.getToId());
      }
      if (!other.getToNick().isEmpty()) {
        toNick_ = other.toNick_;
        onChanged();
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChatRespBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChatRespBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
     */
    public com.liangke.tcp.packet.ChatType getType() {
      com.liangke.tcp.packet.ChatType result = com.liangke.tcp.packet.ChatType.valueOf(type_);
      return result == null ? com.liangke.tcp.packet.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
     */
    public Builder setType(com.liangke.tcp.packet.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private Object text_ = "";
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>string text = 3;</code>
     */
    public String getText() {
      Object ref = text_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>string text = 3;</code>
     */
    public Builder setText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>string text = 3;</code>
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>string text = 3;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private int fromId_ ;
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>int32 fromId = 4;</code>
     */
    public int getFromId() {
      return fromId_;
    }
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>int32 fromId = 4;</code>
     */
    public Builder setFromId(int value) {
      
      fromId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>int32 fromId = 4;</code>
     */
    public Builder clearFromId() {
      
      fromId_ = 0;
      onChanged();
      return this;
    }

    private Object fromHeadUrl_ = "";
    /**
     * <pre>
     *发送聊天信息用户URL
     * </pre>
     *
     * <code>string fromHeadUrl = 5;</code>
     */
    public String getFromHeadUrl() {
      Object ref = fromHeadUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromHeadUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *发送聊天信息用户URL
     * </pre>
     *
     * <code>string fromHeadUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFromHeadUrlBytes() {
      Object ref = fromHeadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromHeadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送聊天信息用户URL
     * </pre>
     *
     * <code>string fromHeadUrl = 5;</code>
     */
    public Builder setFromHeadUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromHeadUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天信息用户URL
     * </pre>
     *
     * <code>string fromHeadUrl = 5;</code>
     */
    public Builder clearFromHeadUrl() {
      
      fromHeadUrl_ = getDefaultInstance().getFromHeadUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天信息用户URL
     * </pre>
     *
     * <code>string fromHeadUrl = 5;</code>
     */
    public Builder setFromHeadUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromHeadUrl_ = value;
      onChanged();
      return this;
    }

    private Object fromNick_ = "";
    /**
     * <pre>
     *发送聊天消息的用户nick
     * </pre>
     *
     * <code>string fromNick = 6;</code>
     */
    public String getFromNick() {
      Object ref = fromNick_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromNick_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *发送聊天消息的用户nick
     * </pre>
     *
     * <code>string fromNick = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFromNickBytes() {
      Object ref = fromNick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromNick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送聊天消息的用户nick
     * </pre>
     *
     * <code>string fromNick = 6;</code>
     */
    public Builder setFromNick(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromNick_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天消息的用户nick
     * </pre>
     *
     * <code>string fromNick = 6;</code>
     */
    public Builder clearFromNick() {
      
      fromNick_ = getDefaultInstance().getFromNick();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天消息的用户nick
     * </pre>
     *
     * <code>string fromNick = 6;</code>
     */
    public Builder setFromNickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromNick_ = value;
      onChanged();
      return this;
    }

    private int toId_ ;
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>int32 toId = 7;</code>
     */
    public int getToId() {
      return toId_;
    }
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>int32 toId = 7;</code>
     */
    public Builder setToId(int value) {
      
      toId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>int32 toId = 7;</code>
     */
    public Builder clearToId() {
      
      toId_ = 0;
      onChanged();
      return this;
    }

    private Object toNick_ = "";
    /**
     * <pre>
     *目标用户nick
     * </pre>
     *
     * <code>string toNick = 8;</code>
     */
    public String getToNick() {
      Object ref = toNick_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toNick_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *目标用户nick
     * </pre>
     *
     * <code>string toNick = 8;</code>
     */
    public com.google.protobuf.ByteString
        getToNickBytes() {
      Object ref = toNick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toNick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *目标用户nick
     * </pre>
     *
     * <code>string toNick = 8;</code>
     */
    public Builder setToNick(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toNick_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标用户nick
     * </pre>
     *
     * <code>string toNick = 8;</code>
     */
    public Builder clearToNick() {
      
      toNick_ = getDefaultInstance().getToNick();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标用户nick
     * </pre>
     *
     * <code>string toNick = 8;</code>
     */
    public Builder setToNickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toNick_ = value;
      onChanged();
      return this;
    }

    private Object group_ = "";
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>string group = 9;</code>
     */
    public String getGroup() {
      Object ref = group_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>string group = 9;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>string group = 9;</code>
     */
    public Builder setGroup(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>string group = 9;</code>
     */
    public Builder clearGroup() {
      
      group_ = getDefaultInstance().getGroup();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>string group = 9;</code>
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      group_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.liangke.tcp.packet.ChatRespBody)
  }

  // @@protoc_insertion_point(class_scope:com.liangke.tcp.packet.ChatRespBody)
  private static final ChatRespBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChatRespBody();
  }

  public static ChatRespBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatRespBody>
      PARSER = new com.google.protobuf.AbstractParser<ChatRespBody>() {
    public ChatRespBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatRespBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatRespBody> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ChatRespBody> getParserForType() {
    return PARSER;
  }

  public ChatRespBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

