// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_AuthReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_AuthReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_AuthRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_AuthRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_JoinReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_JoinReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_JoinRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_JoinRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_ChatReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_ChatReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_ChatRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_MsgPushBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_MsgPushBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_CommodityType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_CommodityType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_QuoteReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_QuoteReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_QuoteRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_QuoteRealPushBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liangke_tcp_packet_QuoteMinPushBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_liangke_tcp_packet_QuoteMinPushBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\022\026com.liangke.tcp.packet\"\304\001\n" +
      "\013AuthReqBody\022\014\n\004time\030\001 \001(\003\022\020\n\010deviceId\030\002" +
      " \001(\t\022\r\n\005token\030\003 \001(\t\0226\n\ndeviceType\030\004 \001(\0162" +
      "\".com.liangke.tcp.packet.DeviceType\022\013\n\003c" +
      "id\030\005 \001(\t\022\022\n\nappVersion\030\006 \001(\t\022\022\n\ndeviceIn" +
      "fo\030\007 \001(\t\022\013\n\003seq\030\010 \001(\003\022\014\n\004sign\030\t \001(\t\"e\n\014A" +
      "uthRespBody\022\014\n\004time\030\001 \001(\003\0222\n\006result\030\002 \001(" +
      "\0162\".com.liangke.tcp.packet.AuthResult\022\023\n" +
      "\013securityKey\030\003 \001(\t\"*\n\013JoinReqBody\022\014\n\004tim" +
      "e\030\001 \001(\003\022\r\n\005group\030\002 \001(\t\"d\n\014JoinRespBody\022\014",
      "\n\004time\030\001 \001(\003\0227\n\006result\030\002 \001(\0162\'.com.liang" +
      "ke.tcp.packet.JoinGroupResult\022\r\n\005group\030\003" +
      " \001(\t\"\206\001\n\013ChatReqBody\022\014\n\004time\030\001 \001(\003\022.\n\004ty" +
      "pe\030\002 \001(\0162 .com.liangke.tcp.packet.ChatTy" +
      "pe\022\014\n\004text\030\003 \001(\t\022\r\n\005group\030\004 \001(\t\022\014\n\004toId\030" +
      "\005 \001(\005\022\016\n\006toNick\030\006 \001(\t\"\276\001\n\014ChatRespBody\022\014" +
      "\n\004time\030\001 \001(\003\022.\n\004type\030\002 \001(\0162 .com.liangke" +
      ".tcp.packet.ChatType\022\014\n\004text\030\003 \001(\t\022\016\n\006fr" +
      "omId\030\004 \001(\005\022\023\n\013fromHeadUrl\030\005 \001(\t\022\020\n\010fromN" +
      "ick\030\006 \001(\t\022\014\n\004toId\030\007 \001(\005\022\016\n\006toNick\030\010 \001(\t\022",
      "\r\n\005group\030\t \001(\t\"g\n\013MsgPushBody\022\014\n\004time\030\001 " +
      "\001(\003\022-\n\004type\030\002 \001(\0162\037.com.liangke.tcp.pack" +
      "et.MsgType\022\r\n\005title\030\003 \001(\t\022\014\n\004text\030\004 \001(\t\"" +
      "K\n\rCommodityType\022\021\n\tproductId\030\001 \001(\t\022\023\n\013c" +
      "ommodityNo\030\002 \001(\t\022\022\n\ncontractNo\030\003 \001(\t\"Z\n\014" +
      "QuoteReqBody\022\014\n\004time\030\001 \001(\003\022<\n\rcommodityT" +
      "ype\030\002 \003(\0132%.com.liangke.tcp.packet.Commo" +
      "dityType\"[\n\rQuoteRespBody\022\014\n\004time\030\001 \001(\003\022" +
      "<\n\rcommodityType\030\002 \003(\0132%.com.liangke.tcp" +
      ".packet.CommodityType\"\371\001\n\021QuoteRealPushB",
      "ody\022\014\n\004time\030\001 \001(\003\022\021\n\tproductId\030\002 \001(\t\022\023\n\013" +
      "commodityNo\030\003 \001(\t\022\022\n\ncontractNo\030\004 \001(\t\022\013\n" +
      "\003ctm\030\005 \001(\003\022\r\n\005close\030\006 \001(\t\022\014\n\004open\030\007 \001(\t\022" +
      "\014\n\004high\030\010 \001(\t\022\013\n\003low\030\t \001(\t\022\016\n\006settle\030\n \001" +
      "(\t\022\013\n\003bid\030\013 \001(\t\022\016\n\006bidQty\030\014 \001(\t\022\013\n\003ask\030\r" +
      " \001(\t\022\016\n\006askQty\030\016 \001(\t\022\013\n\003mid\030\017 \001(\t\"\205\002\n\020Qu" +
      "oteMinPushBody\022\014\n\004time\030\001 \001(\003\022\021\n\tproductI" +
      "d\030\002 \001(\t\022\023\n\013commodityNo\030\003 \001(\t\022\022\n\ncontract" +
      "No\030\004 \001(\t\0224\n\tquoteType\030\005 \001(\0162!.com.liangk" +
      "e.tcp.packet.QuoteType\022\014\n\004uuid\030\006 \001(\t\022\013\n\003",
      "ctm\030\007 \001(\003\022\014\n\004open\030\010 \001(\t\022\r\n\005close\030\t \001(\t\022\014" +
      "\n\004high\030\n \001(\t\022\013\n\003low\030\013 \001(\t\022\016\n\006volume\030\014 \001(" +
      "\t\022\016\n\006amount\030\r \001(\t*z\n\nDeviceType\022\026\n\022DEVIC" +
      "E_TYPE_UNKNOW\020\000\022\022\n\016DEVICE_TYPE_PC\020\001\022\027\n\023D" +
      "EVICE_TYPE_ANDROID\020\002\022\023\n\017DEVICE_TYPE_IOS\020" +
      "\003\022\022\n\016DEVICE_TYPE_H5\020\004*\200\004\n\007Command\022\022\n\016COM" +
      "MAND_UNKNOW\020\000\022\031\n\025COMMAND_HANDSHAKE_REQ\020\001" +
      "\022\032\n\026COMMAND_HANDSHAKE_RESP\020\002\022\024\n\020COMMAND_" +
      "AUTH_REQ\020\003\022\025\n\021COMMAND_AUTH_RESP\020\004\022\032\n\026COM" +
      "MAND_JOIN_GROUP_REQ\020\005\022\033\n\027COMMAND_JOIN_GR",
      "OUP_RESP\020\006\022\"\n\036COMMAND_JOIN_GROUP_NOTIFY_" +
      "RESP\020\007\022\024\n\020COMMAND_CHAT_REQ\020\010\022\025\n\021COMMAND_" +
      "CHAT_RESP\020\t\022\031\n\025COMMAND_QUOTE_ADD_REQ\020\n\022\032" +
      "\n\026COMMAND_QUOTE_ADD_RESP\020\013\022\031\n\025COMMAND_QU" +
      "OTE_DEL_REQ\020\014\022\032\n\026COMMAND_QUOTE_DEL_RESP\020" +
      "\r\022\033\n\027COMMAND_QUOTE_REAL_PUSH\020\016\022\032\n\026COMMAN" +
      "D_QUOTE_MIN_PUSH\020\017\022\032\n\026COMMAND_QUOTE_MSG_" +
      "PUSH\020\020\022\031\n\025COMMAND_HEARTBEAT_REQ\020\021\022\025\n\021COM" +
      "MAND_CLOSE_REQ\020\022*h\n\nAuthResult\022\026\n\022AUTH_R" +
      "ESULT_UNKNOW\020\000\022\022\n\016AUTH_RESULT_OK\020\001\022\024\n\020AU",
      "TH_RESULT_FAIL\020\002\022\030\n\024AUTH_RESULT_REPEATED" +
      "\020\003*\320\001\n\017JoinGroupResult\022\034\n\030JOIN_GROUP_RES" +
      "ULT_UNKNOW\020\000\022\030\n\024JOIN_GROUP_RESULT_OK\020\001\022\037" +
      "\n\033JOIN_GROUP_RESULT_NOT_EXIST\020\002\022 \n\034JOIN_" +
      "GROUP_RESULT_GROUP_FULL\020\003\022!\n\035JOIN_GROUP_" +
      "RESULT_IN_BACKLIST\020\004\022\037\n\033JOIN_GROUP_RESUL" +
      "T_TAKEOUTED\020\005*M\n\010ChatType\022\024\n\020CHAT_TYPE_U" +
      "NKNOW\020\000\022\024\n\020CHAT_TYPE_PUBLIC\020\001\022\025\n\021CHAT_TY" +
      "PE_PRIVATE\020\002*J\n\007MsgType\022\023\n\017MSG_TYPE_UNKN" +
      "OW\020\000\022\025\n\021MSG_TYPE_ANNOUNCE\020\001\022\023\n\017MSG_TYPE_",
      "INFORM\020\002*\215\001\n\tQuoteType\022\026\n\022QUOTE_TYPE_ONE" +
      "_MIN\020\000\022\030\n\024QUOTE_TYPE_THREE_MIN\020\001\022\027\n\023QUOT" +
      "E_TYPE_FIVE_MIN\020\002\022\032\n\026QUOTE_TYPE_FIFTEEN_" +
      "MIN\020\003\022\031\n\025QUOTE_TYPE_THIRTY_MIN\020\004B\032\n\026com." +
      "liangke.tcp.packetP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_liangke_tcp_packet_AuthReqBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_liangke_tcp_packet_AuthReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_AuthReqBody_descriptor,
        new String[] { "Time", "DeviceId", "Token", "DeviceType", "Cid", "AppVersion", "DeviceInfo", "Seq", "Sign", });
    internal_static_com_liangke_tcp_packet_AuthRespBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_liangke_tcp_packet_AuthRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_AuthRespBody_descriptor,
        new String[] { "Time", "Result", "SecurityKey", });
    internal_static_com_liangke_tcp_packet_JoinReqBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_liangke_tcp_packet_JoinReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_JoinReqBody_descriptor,
        new String[] { "Time", "Group", });
    internal_static_com_liangke_tcp_packet_JoinRespBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_liangke_tcp_packet_JoinRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_JoinRespBody_descriptor,
        new String[] { "Time", "Result", "Group", });
    internal_static_com_liangke_tcp_packet_ChatReqBody_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_liangke_tcp_packet_ChatReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_ChatReqBody_descriptor,
        new String[] { "Time", "Type", "Text", "Group", "ToId", "ToNick", });
    internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_liangke_tcp_packet_ChatRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_ChatRespBody_descriptor,
        new String[] { "Time", "Type", "Text", "FromId", "FromHeadUrl", "FromNick", "ToId", "ToNick", "Group", });
    internal_static_com_liangke_tcp_packet_MsgPushBody_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_liangke_tcp_packet_MsgPushBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_MsgPushBody_descriptor,
        new String[] { "Time", "Type", "Title", "Text", });
    internal_static_com_liangke_tcp_packet_CommodityType_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_liangke_tcp_packet_CommodityType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_CommodityType_descriptor,
        new String[] { "ProductId", "CommodityNo", "ContractNo", });
    internal_static_com_liangke_tcp_packet_QuoteReqBody_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_liangke_tcp_packet_QuoteReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_QuoteReqBody_descriptor,
        new String[] { "Time", "CommodityType", });
    internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_liangke_tcp_packet_QuoteRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor,
        new String[] { "Time", "CommodityType", });
    internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_liangke_tcp_packet_QuoteRealPushBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor,
        new String[] { "Time", "ProductId", "CommodityNo", "ContractNo", "Ctm", "Close", "Open", "High", "Low", "Settle", "Bid", "BidQty", "Ask", "AskQty", "Mid", });
    internal_static_com_liangke_tcp_packet_QuoteMinPushBody_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_liangke_tcp_packet_QuoteMinPushBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_liangke_tcp_packet_QuoteMinPushBody_descriptor,
        new String[] { "Time", "ProductId", "CommodityNo", "ContractNo", "QuoteType", "Uuid", "Ctm", "Open", "Close", "High", "Low", "Volume", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
