// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public interface ChatRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.liangke.tcp.packet.ChatRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.com.liangke.tcp.packet.ChatType type = 2;</code>
   */
  com.liangke.tcp.packet.ChatType getType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *发送聊天消息的用户id
   * </pre>
   *
   * <code>int32 fromId = 4;</code>
   */
  int getFromId();

  /**
   * <pre>
   *发送聊天信息用户URL
   * </pre>
   *
   * <code>string fromHeadUrl = 5;</code>
   */
  String getFromHeadUrl();
  /**
   * <pre>
   *发送聊天信息用户URL
   * </pre>
   *
   * <code>string fromHeadUrl = 5;</code>
   */
  com.google.protobuf.ByteString
      getFromHeadUrlBytes();

  /**
   * <pre>
   *发送聊天消息的用户nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  String getFromNick();
  /**
   * <pre>
   *发送聊天消息的用户nick
   * </pre>
   *
   * <code>string fromNick = 6;</code>
   */
  com.google.protobuf.ByteString
      getFromNickBytes();

  /**
   * <pre>
   *目标用户id
   * </pre>
   *
   * <code>int32 toId = 7;</code>
   */
  int getToId();

  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 8;</code>
   */
  String getToNick();
  /**
   * <pre>
   *目标用户nick
   * </pre>
   *
   * <code>string toNick = 8;</code>
   */
  com.google.protobuf.ByteString
      getToNickBytes();

  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 9;</code>
   */
  String getGroup();
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>string group = 9;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
