// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public interface CommodityTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.liangke.tcp.packet.CommodityType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *交易所ID
   * </pre>
   *
   * <code>string productId = 1;</code>
   */
  String getProductId();
  /**
   * <pre>
   *交易所ID
   * </pre>
   *
   * <code>string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <pre>
   * 订阅交易品种类型
   * </pre>
   *
   * <code>string commodityNo = 2;</code>
   */
  String getCommodityNo();
  /**
   * <pre>
   * 订阅交易品种类型
   * </pre>
   *
   * <code>string commodityNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommodityNoBytes();

  /**
   * <pre>
   * 订阅交易品种合约号,若无则为空字符串
   * </pre>
   *
   * <code>string contractNo = 3;</code>
   */
  String getContractNo();
  /**
   * <pre>
   * 订阅交易品种合约号,若无则为空字符串
   * </pre>
   *
   * <code>string contractNo = 3;</code>
   */
  com.google.protobuf.ByteString
      getContractNoBytes();
}
