// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public interface JoinReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.liangke.tcp.packet.JoinReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>string group = 2;</code>
   */
  String getGroup();
  /**
   * <code>string group = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
