// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

/**
 * <pre>
 **
 * 推送消息类型
 * </pre>
 *
 * Protobuf enum {@code com.liangke.tcp.packet.MsgType}
 */
public enum MsgType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *未知
   * </pre>
   *
   * <code>MSG_TYPE_UNKNOW = 0;</code>
   */
  MSG_TYPE_UNKNOW(0),
  /**
   * <pre>
   *公告
   * </pre>
   *
   * <code>MSG_TYPE_ANNOUNCE = 1;</code>
   */
  MSG_TYPE_ANNOUNCE(1),
  /**
   * <pre>
   *通知、消息
   * </pre>
   *
   * <code>MSG_TYPE_INFORM = 2;</code>
   */
  MSG_TYPE_INFORM(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *未知
   * </pre>
   *
   * <code>MSG_TYPE_UNKNOW = 0;</code>
   */
  public static final int MSG_TYPE_UNKNOW_VALUE = 0;
  /**
   * <pre>
   *公告
   * </pre>
   *
   * <code>MSG_TYPE_ANNOUNCE = 1;</code>
   */
  public static final int MSG_TYPE_ANNOUNCE_VALUE = 1;
  /**
   * <pre>
   *通知、消息
   * </pre>
   *
   * <code>MSG_TYPE_INFORM = 2;</code>
   */
  public static final int MSG_TYPE_INFORM_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static MsgType valueOf(int value) {
    return forNumber(value);
  }

  public static MsgType forNumber(int value) {
    switch (value) {
      case 0: return MSG_TYPE_UNKNOW;
      case 1: return MSG_TYPE_ANNOUNCE;
      case 2: return MSG_TYPE_INFORM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MsgType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
          public MsgType findValueByNumber(int number) {
            return MsgType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Chat.getDescriptor().getEnumTypes().get(5);
  }

  private static final MsgType[] VALUES = values();

  public static MsgType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.liangke.tcp.packet.MsgType)
}

