// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

public interface QuoteReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.liangke.tcp.packet.QuoteReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *需要行情订阅或者取消订阅的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  java.util.List<CommodityType>
      getCommodityTypeList();
  /**
   * <pre>
   *需要行情订阅或者取消订阅的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  CommodityType getCommodityType(int index);
  /**
   * <pre>
   *需要行情订阅或者取消订阅的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  int getCommodityTypeCount();
  /**
   * <pre>
   *需要行情订阅或者取消订阅的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  java.util.List<? extends CommodityTypeOrBuilder>
      getCommodityTypeOrBuilderList();
  /**
   * <pre>
   *需要行情订阅或者取消订阅的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  CommodityTypeOrBuilder getCommodityTypeOrBuilder(
          int index);
}
