// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

/**
 * <pre>
 **
 * 实时行情推送
 * </pre>
 *
 * Protobuf type {@code com.liangke.tcp.packet.QuoteRealPushBody}
 */
public  final class QuoteRealPushBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.liangke.tcp.packet.QuoteRealPushBody)
    QuoteRealPushBodyOrBuilder {
  // Use QuoteRealPushBody.newBuilder() to construct.
  private QuoteRealPushBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuoteRealPushBody() {
    time_ = 0L;
    productId_ = "";
    commodityNo_ = "";
    contractNo_ = "";
    ctm_ = 0L;
    close_ = "";
    open_ = "";
    high_ = "";
    low_ = "";
    settle_ = "";
    bid_ = "";
    bidQty_ = "";
    ask_ = "";
    askQty_ = "";
    mid_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private QuoteRealPushBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            productId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            commodityNo_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            contractNo_ = s;
            break;
          }
          case 40: {

            ctm_ = input.readInt64();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            close_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            open_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            high_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            low_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            settle_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            bid_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            bidQty_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            ask_ = s;
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            askQty_ = s;
            break;
          }
          case 122: {
            String s = input.readStringRequireUtf8();

            mid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Chat.internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Chat.internal_static_com_liangke_tcp_packet_QuoteRealPushBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QuoteRealPushBody.class, Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int PRODUCTID_FIELD_NUMBER = 2;
  private volatile Object productId_;
  /**
   * <pre>
   *交易所ID
   * </pre>
   *
   * <code>string productId = 2;</code>
   */
  public String getProductId() {
    Object ref = productId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      productId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *交易所ID
   * </pre>
   *
   * <code>string productId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProductIdBytes() {
    Object ref = productId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      productId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMODITYNO_FIELD_NUMBER = 3;
  private volatile Object commodityNo_;
  /**
   * <pre>
   * 订阅商品类型
   * </pre>
   *
   * <code>string commodityNo = 3;</code>
   */
  public String getCommodityNo() {
    Object ref = commodityNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      commodityNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 订阅商品类型
   * </pre>
   *
   * <code>string commodityNo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCommodityNoBytes() {
    Object ref = commodityNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      commodityNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACTNO_FIELD_NUMBER = 4;
  private volatile Object contractNo_;
  /**
   * <pre>
   * 商品合约号
   * </pre>
   *
   * <code>string contractNo = 4;</code>
   */
  public String getContractNo() {
    Object ref = contractNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      contractNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 商品合约号
   * </pre>
   *
   * <code>string contractNo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getContractNoBytes() {
    Object ref = contractNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      contractNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTM_FIELD_NUMBER = 5;
  private long ctm_;
  /**
   * <pre>
   *行情时间,时间戳
   * </pre>
   *
   * <code>int64 ctm = 5;</code>
   */
  public long getCtm() {
    return ctm_;
  }

  public static final int CLOSE_FIELD_NUMBER = 6;
  private volatile Object close_;
  /**
   * <pre>
   *昨日收盘价
   * </pre>
   *
   * <code>string close = 6;</code>
   */
  public String getClose() {
    Object ref = close_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      close_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *昨日收盘价
   * </pre>
   *
   * <code>string close = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCloseBytes() {
    Object ref = close_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      close_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPEN_FIELD_NUMBER = 7;
  private volatile Object open_;
  /**
   * <pre>
   *今日开盘
   * </pre>
   *
   * <code>string open = 7;</code>
   */
  public String getOpen() {
    Object ref = open_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      open_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *今日开盘
   * </pre>
   *
   * <code>string open = 7;</code>
   */
  public com.google.protobuf.ByteString
      getOpenBytes() {
    Object ref = open_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      open_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGH_FIELD_NUMBER = 8;
  private volatile Object high_;
  /**
   * <pre>
   *今日最高
   * </pre>
   *
   * <code>string high = 8;</code>
   */
  public String getHigh() {
    Object ref = high_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      high_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *今日最高
   * </pre>
   *
   * <code>string high = 8;</code>
   */
  public com.google.protobuf.ByteString
      getHighBytes() {
    Object ref = high_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      high_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOW_FIELD_NUMBER = 9;
  private volatile Object low_;
  /**
   * <pre>
   *今日最低
   * </pre>
   *
   * <code>string low = 9;</code>
   */
  public String getLow() {
    Object ref = low_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      low_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *今日最低
   * </pre>
   *
   * <code>string low = 9;</code>
   */
  public com.google.protobuf.ByteString
      getLowBytes() {
    Object ref = low_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      low_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SETTLE_FIELD_NUMBER = 10;
  private volatile Object settle_;
  /**
   * <pre>
   *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
   * </pre>
   *
   * <code>string settle = 10;</code>
   */
  public String getSettle() {
    Object ref = settle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      settle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
   * </pre>
   *
   * <code>string settle = 10;</code>
   */
  public com.google.protobuf.ByteString
      getSettleBytes() {
    Object ref = settle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      settle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BID_FIELD_NUMBER = 11;
  private volatile Object bid_;
  /**
   * <pre>
   *基准卖价,实时价
   * </pre>
   *
   * <code>string bid = 11;</code>
   */
  public String getBid() {
    Object ref = bid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *基准卖价,实时价
   * </pre>
   *
   * <code>string bid = 11;</code>
   */
  public com.google.protobuf.ByteString
      getBidBytes() {
    Object ref = bid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIDQTY_FIELD_NUMBER = 12;
  private volatile Object bidQty_;
  /**
   * <pre>
   *买涨量
   * </pre>
   *
   * <code>string bidQty = 12;</code>
   */
  public String getBidQty() {
    Object ref = bidQty_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bidQty_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *买涨量
   * </pre>
   *
   * <code>string bidQty = 12;</code>
   */
  public com.google.protobuf.ByteString
      getBidQtyBytes() {
    Object ref = bidQty_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bidQty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASK_FIELD_NUMBER = 13;
  private volatile Object ask_;
  /**
   * <pre>
   *基准买价
   * </pre>
   *
   * <code>string ask = 13;</code>
   */
  public String getAsk() {
    Object ref = ask_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ask_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *基准买价
   * </pre>
   *
   * <code>string ask = 13;</code>
   */
  public com.google.protobuf.ByteString
      getAskBytes() {
    Object ref = ask_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASKQTY_FIELD_NUMBER = 14;
  private volatile Object askQty_;
  /**
   * <pre>
   *买跌量
   * </pre>
   *
   * <code>string askQty = 14;</code>
   */
  public String getAskQty() {
    Object ref = askQty_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      askQty_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *买跌量
   * </pre>
   *
   * <code>string askQty = 14;</code>
   */
  public com.google.protobuf.ByteString
      getAskQtyBytes() {
    Object ref = askQty_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      askQty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MID_FIELD_NUMBER = 15;
  private volatile Object mid_;
  /**
   * <pre>
   *点差 外汇用字段
   * </pre>
   *
   * <code>string mid = 15;</code>
   */
  public String getMid() {
    Object ref = mid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *点差 外汇用字段
   * </pre>
   *
   * <code>string mid = 15;</code>
   */
  public com.google.protobuf.ByteString
      getMidBytes() {
    Object ref = mid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (!getProductIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_);
    }
    if (!getCommodityNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commodityNo_);
    }
    if (!getContractNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contractNo_);
    }
    if (ctm_ != 0L) {
      output.writeInt64(5, ctm_);
    }
    if (!getCloseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, close_);
    }
    if (!getOpenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, open_);
    }
    if (!getHighBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, high_);
    }
    if (!getLowBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, low_);
    }
    if (!getSettleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, settle_);
    }
    if (!getBidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, bid_);
    }
    if (!getBidQtyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, bidQty_);
    }
    if (!getAskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, ask_);
    }
    if (!getAskQtyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, askQty_);
    }
    if (!getMidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, mid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (!getProductIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productId_);
    }
    if (!getCommodityNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commodityNo_);
    }
    if (!getContractNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, contractNo_);
    }
    if (ctm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, ctm_);
    }
    if (!getCloseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, close_);
    }
    if (!getOpenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, open_);
    }
    if (!getHighBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, high_);
    }
    if (!getLowBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, low_);
    }
    if (!getSettleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, settle_);
    }
    if (!getBidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, bid_);
    }
    if (!getBidQtyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, bidQty_);
    }
    if (!getAskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, ask_);
    }
    if (!getAskQtyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, askQty_);
    }
    if (!getMidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, mid_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QuoteRealPushBody)) {
      return super.equals(obj);
    }
    QuoteRealPushBody other = (QuoteRealPushBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && getProductId()
        .equals(other.getProductId());
    result = result && getCommodityNo()
        .equals(other.getCommodityNo());
    result = result && getContractNo()
        .equals(other.getContractNo());
    result = result && (getCtm()
        == other.getCtm());
    result = result && getClose()
        .equals(other.getClose());
    result = result && getOpen()
        .equals(other.getOpen());
    result = result && getHigh()
        .equals(other.getHigh());
    result = result && getLow()
        .equals(other.getLow());
    result = result && getSettle()
        .equals(other.getSettle());
    result = result && getBid()
        .equals(other.getBid());
    result = result && getBidQty()
        .equals(other.getBidQty());
    result = result && getAsk()
        .equals(other.getAsk());
    result = result && getAskQty()
        .equals(other.getAskQty());
    result = result && getMid()
        .equals(other.getMid());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId().hashCode();
    hash = (37 * hash) + COMMODITYNO_FIELD_NUMBER;
    hash = (53 * hash) + getCommodityNo().hashCode();
    hash = (37 * hash) + CONTRACTNO_FIELD_NUMBER;
    hash = (53 * hash) + getContractNo().hashCode();
    hash = (37 * hash) + CTM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCtm());
    hash = (37 * hash) + CLOSE_FIELD_NUMBER;
    hash = (53 * hash) + getClose().hashCode();
    hash = (37 * hash) + OPEN_FIELD_NUMBER;
    hash = (53 * hash) + getOpen().hashCode();
    hash = (37 * hash) + HIGH_FIELD_NUMBER;
    hash = (53 * hash) + getHigh().hashCode();
    hash = (37 * hash) + LOW_FIELD_NUMBER;
    hash = (53 * hash) + getLow().hashCode();
    hash = (37 * hash) + SETTLE_FIELD_NUMBER;
    hash = (53 * hash) + getSettle().hashCode();
    hash = (37 * hash) + BID_FIELD_NUMBER;
    hash = (53 * hash) + getBid().hashCode();
    hash = (37 * hash) + BIDQTY_FIELD_NUMBER;
    hash = (53 * hash) + getBidQty().hashCode();
    hash = (37 * hash) + ASK_FIELD_NUMBER;
    hash = (53 * hash) + getAsk().hashCode();
    hash = (37 * hash) + ASKQTY_FIELD_NUMBER;
    hash = (53 * hash) + getAskQty().hashCode();
    hash = (37 * hash) + MID_FIELD_NUMBER;
    hash = (53 * hash) + getMid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QuoteRealPushBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuoteRealPushBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuoteRealPushBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuoteRealPushBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuoteRealPushBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuoteRealPushBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuoteRealPushBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QuoteRealPushBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuoteRealPushBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuoteRealPushBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QuoteRealPushBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 实时行情推送
   * </pre>
   *
   * Protobuf type {@code com.liangke.tcp.packet.QuoteRealPushBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.liangke.tcp.packet.QuoteRealPushBody)
      com.liangke.tcp.packet.QuoteRealPushBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRealPushBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuoteRealPushBody.class, Builder.class);
    }

    // Construct using com.liangke.tcp.packet.QuoteRealPushBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      productId_ = "";

      commodityNo_ = "";

      contractNo_ = "";

      ctm_ = 0L;

      close_ = "";

      open_ = "";

      high_ = "";

      low_ = "";

      settle_ = "";

      bid_ = "";

      bidQty_ = "";

      ask_ = "";

      askQty_ = "";

      mid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRealPushBody_descriptor;
    }

    public QuoteRealPushBody getDefaultInstanceForType() {
      return QuoteRealPushBody.getDefaultInstance();
    }

    public QuoteRealPushBody build() {
      QuoteRealPushBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public QuoteRealPushBody buildPartial() {
      QuoteRealPushBody result = new QuoteRealPushBody(this);
      result.time_ = time_;
      result.productId_ = productId_;
      result.commodityNo_ = commodityNo_;
      result.contractNo_ = contractNo_;
      result.ctm_ = ctm_;
      result.close_ = close_;
      result.open_ = open_;
      result.high_ = high_;
      result.low_ = low_;
      result.settle_ = settle_;
      result.bid_ = bid_;
      result.bidQty_ = bidQty_;
      result.ask_ = ask_;
      result.askQty_ = askQty_;
      result.mid_ = mid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QuoteRealPushBody) {
        return mergeFrom((QuoteRealPushBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QuoteRealPushBody other) {
      if (other == QuoteRealPushBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (!other.getProductId().isEmpty()) {
        productId_ = other.productId_;
        onChanged();
      }
      if (!other.getCommodityNo().isEmpty()) {
        commodityNo_ = other.commodityNo_;
        onChanged();
      }
      if (!other.getContractNo().isEmpty()) {
        contractNo_ = other.contractNo_;
        onChanged();
      }
      if (other.getCtm() != 0L) {
        setCtm(other.getCtm());
      }
      if (!other.getClose().isEmpty()) {
        close_ = other.close_;
        onChanged();
      }
      if (!other.getOpen().isEmpty()) {
        open_ = other.open_;
        onChanged();
      }
      if (!other.getHigh().isEmpty()) {
        high_ = other.high_;
        onChanged();
      }
      if (!other.getLow().isEmpty()) {
        low_ = other.low_;
        onChanged();
      }
      if (!other.getSettle().isEmpty()) {
        settle_ = other.settle_;
        onChanged();
      }
      if (!other.getBid().isEmpty()) {
        bid_ = other.bid_;
        onChanged();
      }
      if (!other.getBidQty().isEmpty()) {
        bidQty_ = other.bidQty_;
        onChanged();
      }
      if (!other.getAsk().isEmpty()) {
        ask_ = other.ask_;
        onChanged();
      }
      if (!other.getAskQty().isEmpty()) {
        askQty_ = other.askQty_;
        onChanged();
      }
      if (!other.getMid().isEmpty()) {
        mid_ = other.mid_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QuoteRealPushBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QuoteRealPushBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private Object productId_ = "";
    /**
     * <pre>
     *交易所ID
     * </pre>
     *
     * <code>string productId = 2;</code>
     */
    public String getProductId() {
      Object ref = productId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *交易所ID
     * </pre>
     *
     * <code>string productId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      Object ref = productId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *交易所ID
     * </pre>
     *
     * <code>string productId = 2;</code>
     */
    public Builder setProductId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易所ID
     * </pre>
     *
     * <code>string productId = 2;</code>
     */
    public Builder clearProductId() {
      
      productId_ = getDefaultInstance().getProductId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易所ID
     * </pre>
     *
     * <code>string productId = 2;</code>
     */
    public Builder setProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productId_ = value;
      onChanged();
      return this;
    }

    private Object commodityNo_ = "";
    /**
     * <pre>
     * 订阅商品类型
     * </pre>
     *
     * <code>string commodityNo = 3;</code>
     */
    public String getCommodityNo() {
      Object ref = commodityNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commodityNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 订阅商品类型
     * </pre>
     *
     * <code>string commodityNo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommodityNoBytes() {
      Object ref = commodityNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commodityNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 订阅商品类型
     * </pre>
     *
     * <code>string commodityNo = 3;</code>
     */
    public Builder setCommodityNo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commodityNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订阅商品类型
     * </pre>
     *
     * <code>string commodityNo = 3;</code>
     */
    public Builder clearCommodityNo() {
      
      commodityNo_ = getDefaultInstance().getCommodityNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订阅商品类型
     * </pre>
     *
     * <code>string commodityNo = 3;</code>
     */
    public Builder setCommodityNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commodityNo_ = value;
      onChanged();
      return this;
    }

    private Object contractNo_ = "";
    /**
     * <pre>
     * 商品合约号
     * </pre>
     *
     * <code>string contractNo = 4;</code>
     */
    public String getContractNo() {
      Object ref = contractNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        contractNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 商品合约号
     * </pre>
     *
     * <code>string contractNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContractNoBytes() {
      Object ref = contractNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        contractNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 商品合约号
     * </pre>
     *
     * <code>string contractNo = 4;</code>
     */
    public Builder setContractNo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 商品合约号
     * </pre>
     *
     * <code>string contractNo = 4;</code>
     */
    public Builder clearContractNo() {
      
      contractNo_ = getDefaultInstance().getContractNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 商品合约号
     * </pre>
     *
     * <code>string contractNo = 4;</code>
     */
    public Builder setContractNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractNo_ = value;
      onChanged();
      return this;
    }

    private long ctm_ ;
    /**
     * <pre>
     *行情时间,时间戳
     * </pre>
     *
     * <code>int64 ctm = 5;</code>
     */
    public long getCtm() {
      return ctm_;
    }
    /**
     * <pre>
     *行情时间,时间戳
     * </pre>
     *
     * <code>int64 ctm = 5;</code>
     */
    public Builder setCtm(long value) {
      
      ctm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *行情时间,时间戳
     * </pre>
     *
     * <code>int64 ctm = 5;</code>
     */
    public Builder clearCtm() {
      
      ctm_ = 0L;
      onChanged();
      return this;
    }

    private Object close_ = "";
    /**
     * <pre>
     *昨日收盘价
     * </pre>
     *
     * <code>string close = 6;</code>
     */
    public String getClose() {
      Object ref = close_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        close_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *昨日收盘价
     * </pre>
     *
     * <code>string close = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCloseBytes() {
      Object ref = close_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        close_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *昨日收盘价
     * </pre>
     *
     * <code>string close = 6;</code>
     */
    public Builder setClose(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      close_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *昨日收盘价
     * </pre>
     *
     * <code>string close = 6;</code>
     */
    public Builder clearClose() {
      
      close_ = getDefaultInstance().getClose();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *昨日收盘价
     * </pre>
     *
     * <code>string close = 6;</code>
     */
    public Builder setCloseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      close_ = value;
      onChanged();
      return this;
    }

    private Object open_ = "";
    /**
     * <pre>
     *今日开盘
     * </pre>
     *
     * <code>string open = 7;</code>
     */
    public String getOpen() {
      Object ref = open_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        open_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *今日开盘
     * </pre>
     *
     * <code>string open = 7;</code>
     */
    public com.google.protobuf.ByteString
        getOpenBytes() {
      Object ref = open_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        open_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *今日开盘
     * </pre>
     *
     * <code>string open = 7;</code>
     */
    public Builder setOpen(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      open_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日开盘
     * </pre>
     *
     * <code>string open = 7;</code>
     */
    public Builder clearOpen() {
      
      open_ = getDefaultInstance().getOpen();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日开盘
     * </pre>
     *
     * <code>string open = 7;</code>
     */
    public Builder setOpenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      open_ = value;
      onChanged();
      return this;
    }

    private Object high_ = "";
    /**
     * <pre>
     *今日最高
     * </pre>
     *
     * <code>string high = 8;</code>
     */
    public String getHigh() {
      Object ref = high_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        high_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *今日最高
     * </pre>
     *
     * <code>string high = 8;</code>
     */
    public com.google.protobuf.ByteString
        getHighBytes() {
      Object ref = high_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        high_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *今日最高
     * </pre>
     *
     * <code>string high = 8;</code>
     */
    public Builder setHigh(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      high_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日最高
     * </pre>
     *
     * <code>string high = 8;</code>
     */
    public Builder clearHigh() {
      
      high_ = getDefaultInstance().getHigh();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日最高
     * </pre>
     *
     * <code>string high = 8;</code>
     */
    public Builder setHighBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      high_ = value;
      onChanged();
      return this;
    }

    private Object low_ = "";
    /**
     * <pre>
     *今日最低
     * </pre>
     *
     * <code>string low = 9;</code>
     */
    public String getLow() {
      Object ref = low_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        low_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *今日最低
     * </pre>
     *
     * <code>string low = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLowBytes() {
      Object ref = low_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        low_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *今日最低
     * </pre>
     *
     * <code>string low = 9;</code>
     */
    public Builder setLow(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      low_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日最低
     * </pre>
     *
     * <code>string low = 9;</code>
     */
    public Builder clearLow() {
      
      low_ = getDefaultInstance().getLow();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *今日最低
     * </pre>
     *
     * <code>string low = 9;</code>
     */
    public Builder setLowBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      low_ = value;
      onChanged();
      return this;
    }

    private Object settle_ = "";
    /**
     * <pre>
     *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
     * </pre>
     *
     * <code>string settle = 10;</code>
     */
    public String getSettle() {
      Object ref = settle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        settle_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
     * </pre>
     *
     * <code>string settle = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSettleBytes() {
      Object ref = settle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        settle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
     * </pre>
     *
     * <code>string settle = 10;</code>
     */
    public Builder setSettle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      settle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
     * </pre>
     *
     * <code>string settle = 10;</code>
     */
    public Builder clearSettle() {
      
      settle_ = getDefaultInstance().getSettle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *结算涨跌幅,涨跌率的基本价格(期货是结算价,股票是收市价,放入这个字段)
     * </pre>
     *
     * <code>string settle = 10;</code>
     */
    public Builder setSettleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      settle_ = value;
      onChanged();
      return this;
    }

    private Object bid_ = "";
    /**
     * <pre>
     *基准卖价,实时价
     * </pre>
     *
     * <code>string bid = 11;</code>
     */
    public String getBid() {
      Object ref = bid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *基准卖价,实时价
     * </pre>
     *
     * <code>string bid = 11;</code>
     */
    public com.google.protobuf.ByteString
        getBidBytes() {
      Object ref = bid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *基准卖价,实时价
     * </pre>
     *
     * <code>string bid = 11;</code>
     */
    public Builder setBid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基准卖价,实时价
     * </pre>
     *
     * <code>string bid = 11;</code>
     */
    public Builder clearBid() {
      
      bid_ = getDefaultInstance().getBid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基准卖价,实时价
     * </pre>
     *
     * <code>string bid = 11;</code>
     */
    public Builder setBidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bid_ = value;
      onChanged();
      return this;
    }

    private Object bidQty_ = "";
    /**
     * <pre>
     *买涨量
     * </pre>
     *
     * <code>string bidQty = 12;</code>
     */
    public String getBidQty() {
      Object ref = bidQty_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bidQty_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *买涨量
     * </pre>
     *
     * <code>string bidQty = 12;</code>
     */
    public com.google.protobuf.ByteString
        getBidQtyBytes() {
      Object ref = bidQty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bidQty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *买涨量
     * </pre>
     *
     * <code>string bidQty = 12;</code>
     */
    public Builder setBidQty(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bidQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *买涨量
     * </pre>
     *
     * <code>string bidQty = 12;</code>
     */
    public Builder clearBidQty() {
      
      bidQty_ = getDefaultInstance().getBidQty();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *买涨量
     * </pre>
     *
     * <code>string bidQty = 12;</code>
     */
    public Builder setBidQtyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bidQty_ = value;
      onChanged();
      return this;
    }

    private Object ask_ = "";
    /**
     * <pre>
     *基准买价
     * </pre>
     *
     * <code>string ask = 13;</code>
     */
    public String getAsk() {
      Object ref = ask_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ask_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *基准买价
     * </pre>
     *
     * <code>string ask = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAskBytes() {
      Object ref = ask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *基准买价
     * </pre>
     *
     * <code>string ask = 13;</code>
     */
    public Builder setAsk(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ask_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基准买价
     * </pre>
     *
     * <code>string ask = 13;</code>
     */
    public Builder clearAsk() {
      
      ask_ = getDefaultInstance().getAsk();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基准买价
     * </pre>
     *
     * <code>string ask = 13;</code>
     */
    public Builder setAskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ask_ = value;
      onChanged();
      return this;
    }

    private Object askQty_ = "";
    /**
     * <pre>
     *买跌量
     * </pre>
     *
     * <code>string askQty = 14;</code>
     */
    public String getAskQty() {
      Object ref = askQty_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        askQty_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *买跌量
     * </pre>
     *
     * <code>string askQty = 14;</code>
     */
    public com.google.protobuf.ByteString
        getAskQtyBytes() {
      Object ref = askQty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        askQty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *买跌量
     * </pre>
     *
     * <code>string askQty = 14;</code>
     */
    public Builder setAskQty(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      askQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *买跌量
     * </pre>
     *
     * <code>string askQty = 14;</code>
     */
    public Builder clearAskQty() {
      
      askQty_ = getDefaultInstance().getAskQty();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *买跌量
     * </pre>
     *
     * <code>string askQty = 14;</code>
     */
    public Builder setAskQtyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      askQty_ = value;
      onChanged();
      return this;
    }

    private Object mid_ = "";
    /**
     * <pre>
     *点差 外汇用字段
     * </pre>
     *
     * <code>string mid = 15;</code>
     */
    public String getMid() {
      Object ref = mid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *点差 外汇用字段
     * </pre>
     *
     * <code>string mid = 15;</code>
     */
    public com.google.protobuf.ByteString
        getMidBytes() {
      Object ref = mid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *点差 外汇用字段
     * </pre>
     *
     * <code>string mid = 15;</code>
     */
    public Builder setMid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *点差 外汇用字段
     * </pre>
     *
     * <code>string mid = 15;</code>
     */
    public Builder clearMid() {
      
      mid_ = getDefaultInstance().getMid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *点差 外汇用字段
     * </pre>
     *
     * <code>string mid = 15;</code>
     */
    public Builder setMidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.liangke.tcp.packet.QuoteRealPushBody)
  }

  // @@protoc_insertion_point(class_scope:com.liangke.tcp.packet.QuoteRealPushBody)
  private static final QuoteRealPushBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QuoteRealPushBody();
  }

  public static QuoteRealPushBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuoteRealPushBody>
      PARSER = new com.google.protobuf.AbstractParser<QuoteRealPushBody>() {
    public QuoteRealPushBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuoteRealPushBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuoteRealPushBody> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QuoteRealPushBody> getParserForType() {
    return PARSER;
  }

  public QuoteRealPushBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

