// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.liangke.tcp.packet;

/**
 * <pre>
 **
 * 行情订阅和取消订阅响应
 * </pre>
 *
 * Protobuf type {@code com.liangke.tcp.packet.QuoteRespBody}
 */
public  final class QuoteRespBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.liangke.tcp.packet.QuoteRespBody)
    QuoteRespBodyOrBuilder {
  // Use QuoteRespBody.newBuilder() to construct.
  private QuoteRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuoteRespBody() {
    time_ = 0L;
    commodityType_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private QuoteRespBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              commodityType_ = new java.util.ArrayList<CommodityType>();
              mutable_bitField0_ |= 0x00000002;
            }
            commodityType_.add(
                input.readMessage(CommodityType.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        commodityType_ = java.util.Collections.unmodifiableList(commodityType_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Chat.internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Chat.internal_static_com_liangke_tcp_packet_QuoteRespBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QuoteRespBody.class, Builder.class);
  }

  private int bitField0_;
  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int COMMODITYTYPE_FIELD_NUMBER = 2;
  private java.util.List<CommodityType> commodityType_;
  /**
   * <pre>
   *行情订阅成功或者取消订阅成功的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  public java.util.List<CommodityType> getCommodityTypeList() {
    return commodityType_;
  }
  /**
   * <pre>
   *行情订阅成功或者取消订阅成功的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  public java.util.List<? extends CommodityTypeOrBuilder>
      getCommodityTypeOrBuilderList() {
    return commodityType_;
  }
  /**
   * <pre>
   *行情订阅成功或者取消订阅成功的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  public int getCommodityTypeCount() {
    return commodityType_.size();
  }
  /**
   * <pre>
   *行情订阅成功或者取消订阅成功的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  public CommodityType getCommodityType(int index) {
    return commodityType_.get(index);
  }
  /**
   * <pre>
   *行情订阅成功或者取消订阅成功的品种类型
   * </pre>
   *
   * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
   */
  public CommodityTypeOrBuilder getCommodityTypeOrBuilder(
      int index) {
    return commodityType_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    for (int i = 0; i < commodityType_.size(); i++) {
      output.writeMessage(2, commodityType_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    for (int i = 0; i < commodityType_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, commodityType_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QuoteRespBody)) {
      return super.equals(obj);
    }
    QuoteRespBody other = (QuoteRespBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && getCommodityTypeList()
        .equals(other.getCommodityTypeList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    if (getCommodityTypeCount() > 0) {
      hash = (37 * hash) + COMMODITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCommodityTypeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QuoteRespBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuoteRespBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuoteRespBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QuoteRespBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QuoteRespBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuoteRespBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuoteRespBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QuoteRespBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QuoteRespBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QuoteRespBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QuoteRespBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 行情订阅和取消订阅响应
   * </pre>
   *
   * Protobuf type {@code com.liangke.tcp.packet.QuoteRespBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.liangke.tcp.packet.QuoteRespBody)
      com.liangke.tcp.packet.QuoteRespBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRespBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuoteRespBody.class, Builder.class);
    }

    // Construct using com.liangke.tcp.packet.QuoteRespBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommodityTypeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      if (commodityTypeBuilder_ == null) {
        commodityType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        commodityTypeBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Chat.internal_static_com_liangke_tcp_packet_QuoteRespBody_descriptor;
    }

    public QuoteRespBody getDefaultInstanceForType() {
      return QuoteRespBody.getDefaultInstance();
    }

    public QuoteRespBody build() {
      QuoteRespBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public QuoteRespBody buildPartial() {
      QuoteRespBody result = new QuoteRespBody(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.time_ = time_;
      if (commodityTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          commodityType_ = java.util.Collections.unmodifiableList(commodityType_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.commodityType_ = commodityType_;
      } else {
        result.commodityType_ = commodityTypeBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QuoteRespBody) {
        return mergeFrom((QuoteRespBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QuoteRespBody other) {
      if (other == QuoteRespBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (commodityTypeBuilder_ == null) {
        if (!other.commodityType_.isEmpty()) {
          if (commodityType_.isEmpty()) {
            commodityType_ = other.commodityType_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCommodityTypeIsMutable();
            commodityType_.addAll(other.commodityType_);
          }
          onChanged();
        }
      } else {
        if (!other.commodityType_.isEmpty()) {
          if (commodityTypeBuilder_.isEmpty()) {
            commodityTypeBuilder_.dispose();
            commodityTypeBuilder_ = null;
            commodityType_ = other.commodityType_;
            bitField0_ = (bitField0_ & ~0x00000002);
            commodityTypeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommodityTypeFieldBuilder() : null;
          } else {
            commodityTypeBuilder_.addAllMessages(other.commodityType_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QuoteRespBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QuoteRespBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<CommodityType> commodityType_ =
      java.util.Collections.emptyList();
    private void ensureCommodityTypeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        commodityType_ = new java.util.ArrayList<CommodityType>(commodityType_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        CommodityType, CommodityType.Builder, CommodityTypeOrBuilder> commodityTypeBuilder_;

    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public java.util.List<CommodityType> getCommodityTypeList() {
      if (commodityTypeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commodityType_);
      } else {
        return commodityTypeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public int getCommodityTypeCount() {
      if (commodityTypeBuilder_ == null) {
        return commodityType_.size();
      } else {
        return commodityTypeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public CommodityType getCommodityType(int index) {
      if (commodityTypeBuilder_ == null) {
        return commodityType_.get(index);
      } else {
        return commodityTypeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder setCommodityType(
        int index, CommodityType value) {
      if (commodityTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommodityTypeIsMutable();
        commodityType_.set(index, value);
        onChanged();
      } else {
        commodityTypeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder setCommodityType(
        int index, CommodityType.Builder builderForValue) {
      if (commodityTypeBuilder_ == null) {
        ensureCommodityTypeIsMutable();
        commodityType_.set(index, builderForValue.build());
        onChanged();
      } else {
        commodityTypeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder addCommodityType(CommodityType value) {
      if (commodityTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommodityTypeIsMutable();
        commodityType_.add(value);
        onChanged();
      } else {
        commodityTypeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder addCommodityType(
        int index, CommodityType value) {
      if (commodityTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommodityTypeIsMutable();
        commodityType_.add(index, value);
        onChanged();
      } else {
        commodityTypeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder addCommodityType(
        CommodityType.Builder builderForValue) {
      if (commodityTypeBuilder_ == null) {
        ensureCommodityTypeIsMutable();
        commodityType_.add(builderForValue.build());
        onChanged();
      } else {
        commodityTypeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder addCommodityType(
        int index, CommodityType.Builder builderForValue) {
      if (commodityTypeBuilder_ == null) {
        ensureCommodityTypeIsMutable();
        commodityType_.add(index, builderForValue.build());
        onChanged();
      } else {
        commodityTypeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder addAllCommodityType(
        Iterable<? extends CommodityType> values) {
      if (commodityTypeBuilder_ == null) {
        ensureCommodityTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commodityType_);
        onChanged();
      } else {
        commodityTypeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder clearCommodityType() {
      if (commodityTypeBuilder_ == null) {
        commodityType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        commodityTypeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public Builder removeCommodityType(int index) {
      if (commodityTypeBuilder_ == null) {
        ensureCommodityTypeIsMutable();
        commodityType_.remove(index);
        onChanged();
      } else {
        commodityTypeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public CommodityType.Builder getCommodityTypeBuilder(
        int index) {
      return getCommodityTypeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public CommodityTypeOrBuilder getCommodityTypeOrBuilder(
        int index) {
      if (commodityTypeBuilder_ == null) {
        return commodityType_.get(index);  } else {
        return commodityTypeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public java.util.List<? extends CommodityTypeOrBuilder>
         getCommodityTypeOrBuilderList() {
      if (commodityTypeBuilder_ != null) {
        return commodityTypeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commodityType_);
      }
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public CommodityType.Builder addCommodityTypeBuilder() {
      return getCommodityTypeFieldBuilder().addBuilder(
          CommodityType.getDefaultInstance());
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public CommodityType.Builder addCommodityTypeBuilder(
        int index) {
      return getCommodityTypeFieldBuilder().addBuilder(
          index, CommodityType.getDefaultInstance());
    }
    /**
     * <pre>
     *行情订阅成功或者取消订阅成功的品种类型
     * </pre>
     *
     * <code>repeated .com.liangke.tcp.packet.CommodityType commodityType = 2;</code>
     */
    public java.util.List<CommodityType.Builder>
         getCommodityTypeBuilderList() {
      return getCommodityTypeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        CommodityType, CommodityType.Builder, CommodityTypeOrBuilder>
        getCommodityTypeFieldBuilder() {
      if (commodityTypeBuilder_ == null) {
        commodityTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            CommodityType, CommodityType.Builder, CommodityTypeOrBuilder>(
                commodityType_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        commodityType_ = null;
      }
      return commodityTypeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.liangke.tcp.packet.QuoteRespBody)
  }

  // @@protoc_insertion_point(class_scope:com.liangke.tcp.packet.QuoteRespBody)
  private static final QuoteRespBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QuoteRespBody();
  }

  public static QuoteRespBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuoteRespBody>
      PARSER = new com.google.protobuf.AbstractParser<QuoteRespBody>() {
    public QuoteRespBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuoteRespBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuoteRespBody> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QuoteRespBody> getParserForType() {
    return PARSER;
  }

  public QuoteRespBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

